<script>
    let names=["Honda","Ford","BMW","Nissan"]
    let data=["We aim to connect with brand enthusiasts and a new generation of customers by showcasing Honda values of offering Innovative and Futuristic Technology products. Every Honda car is designed keeping superior customer experience at the core, to help people make their lives better today and into future. Honda shows how it is forever determined to meet and exceed the expectations of customers.The concept of the campaign is deeply rooted in customer insight. Honda understands that before buying a car, people go through the loop of exploration and evaluation. They are overwhelmed with anticipation, reviews, comparisons, recommendations. The exploration is not about buying alone but also service, ownership and maintenance. They have a lot of expectation from the brands.Honda promises to go the extra mile to make sure that every Honda journey is a joy and delight for its customers. And this goes much beyond just the drive, the engineering and the cars. It is a commitment to every side of the ownership experience. Honda fulfills all expectations, delighting the customer at every touchpoint throughout their relationship and therefore 'A Honda Goes Beyond'.","Ford is a family company, one that spans the globe and has shared ideals. We value service to each other and the world as much as to our customers. Generations have made their memories with us and included us in their hopes and dreams. After 117 years, we’re used to adapting to and leading change. That’s why we’re evolving to focus on services, experiences and software as well as vehicles.","The special fascination of the BMW Group not only lies in its products and technology, but also in the company’s history, written by inventors, pioneers and brilliant designers. Today, the BMW Group, with more than 30 production and assembly facilities as well as a global sales network, is the world’s leading manufacturer of premium automobiles and motorcycles, and provider of premium financial and mobility services.","Nissan continues its quest to optimize product development and deliver highly innovative technology. Today, in various countries and regions around the world, we enjoy a stellar reputation for creating truly innovative vehicles and service programs.A pioneer in electric vehicles, Nissan has not only made them affordable but also more practical by investing in charging infrastructure and energy management. We'll continue to offer a variety of exciting EVs by accelerating electrification and technological innovation.Through the development of advanced driver-assistance technologies, we aim to diversify transportation and ultimately aim to reduce the number of deaths in avoidable accidents involving Nissan vehicles to virtually zero."]
    export let indVal;
</script>
<main class="p-4 text-blue-900">
    <h1 style="font-size:90px">{names[indVal]}</h1>
	{data[indVal]}
</main>

<style>
	
</style>